name: x64 Linux CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make test-all "RUN_TESTS=\$(RUN_TESTS_STOP_ON_FAIL)" -j2
