name: Cygwin CI

on:
  push:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install cygwin with chocolatey
        run: |
          choco install cygwin -y
      - name: Install cygwin packages
        run: |
          choco install cyg-get -y
          cyg-get gcc-core make
      - name: check
        run: |
          C:\tools\cygwin\bin\usr\gcc --version
          make --version
      - uses: actions/checkout@v2
      - name: make
        run: make test-all
